// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductStore.Infrastructure.Data;

#nullable disable

namespace ProductStore.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductStore.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("183d8d41-9fb2-4cbe-b800-76dae6d13d7a"),
                            Description = "Very Expensive",
                            Name = "Iphone"
                        },
                        new
                        {
                            Id = new Guid("e00cc1dc-fd12-4195-9cb4-8e3925a5c870"),
                            Description = "Not Expensive",
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = new Guid("b2e3ef6f-a532-460b-9c5b-5f0bf5e06376"),
                            Description = "Very Cheap",
                            Name = "Nokia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
